# Generated by Django 4.1.2 on 2023-07-10 07:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('region_id', models.AutoField(primary_key=True, serialize=False)),
                ('region_txt', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('region_code', models.CharField(blank=True, default=None, max_length=10, null=True)),
                ('region_status', models.IntegerField(blank=True, default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserLevel',
            fields=[
                ('level_id', models.AutoField(primary_key=True, serialize=False)),
                ('level_name', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('avalableUserLevel', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ForestUser',
            fields=[
                ('forest_user_id', models.AutoField(primary_key=True, serialize=False)),
                ('account_status', models.BooleanField(default=True)),
                ('last_login_time', models.DateTimeField(auto_now=True)),
                ('contact_no', models.IntegerField(blank=True, default=None, null=True)),
                ('User', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('level_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users_level_list', to='process.userlevel')),
                ('region_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='region_id_list', to='process.region')),
            ],
        ),
    ]
