# Generated by Django 4.1.2 on 2023-07-11 05:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0002_forestletter'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoupWorkProgram',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('forest_ref', models.CharField(max_length=200, unique=True)),
                ('region', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('beat', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('d_s_d', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('g_s_d', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('village', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('b_s_d', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('extent', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('present_sp', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('plant_sp', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('enter_date', models.DateField(blank=True, default=None, null=True)),
                ('entered_user', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('foresr_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forest_Id', to='process.forestletter')),
            ],
        ),
    ]
