# Generated by Django 4.1.2 on 2023-07-11 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0003_coupworkprogram'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forestletter',
            name='added_date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='forestletter',
            name='issued_date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='forestletter',
            name='received_date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
