# Generated by Django 4.1.2 on 2023-07-11 07:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0004_alter_forestletter_added_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LetterToRM',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('letter_date', models.DateField(blank=True, default=None, null=True)),
                ('form_ref_no', models.CharField(max_length=200, unique=True)),
                ('full_letter', models.CharField(blank=True, default=None, max_length=10000, null=True)),
                ('letter_my_no', models.CharField(max_length=200, unique=True)),
                ('form_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='letter_to_rm_Id', to='process.forestletter')),
            ],
        ),
    ]
