# Generated by Django 4.1.3 on 2023-07-12 05:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0006_lettertemplate_scheduleitems'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coupworkprogram',
            old_name='foresr_id',
            new_name='forest_id',
        ),
        migrations.AlterField(
            model_name='scheduleitems',
            name='item_order',
            field=models.IntegerField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('schedule_id', models.AutoField(primary_key=True, serialize=False)),
                ('no_of_dates', models.IntegerField(blank=True, default=None, max_length=10000, null=True)),
                ('from_date', models.DateField(blank=True, default=None, null=True)),
                ('to_date', models.DateField(blank=True, default=None, null=True)),
                ('item_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_items_reference', to='process.scheduleitems')),
            ],
        ),
    ]
