# Generated by Django 4.1.2 on 2023-07-17 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0007_rename_foresr_id_coupworkprogram_forest_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='no_of_dates',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='scheduleitems',
            name='item_order',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
