# Generated by Django 4.1.2 on 2023-07-17 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0008_alter_schedule_no_of_dates_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forestletter',
            name='original_excel',
            field=models.FileField(blank=True, default=None, max_length=200, null=True, upload_to=''),
        ),
    ]
