# Generated by Django 4.1.2 on 2023-07-27 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0010_excelfile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ExcelFile',
        ),
    ]
