# Generated by Django 4.1.1 on 2023-08-03 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0011_delete_excelfile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(blank=True, null=True, upload_to='media/%Y/%m/%d/')),
            ],
        ),
    ]
