# Generated by Django 4.1.2 on 2023-08-10 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0012_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
